#!/usr/bin/env python3
"""
IEEE/TRO-style Greenhouse VLA decision-process plots.

Inputs generated by evaluate_model_offline_fixed.py:
  - predictions.csv
  - metrics.json

Figures generated:
  - fig_vlm_decision_timeline.{png,pdf}
  - fig_vlm_state_action_storyboard.{png,pdf}
  - fig_vlm_metrics_summary.{png,pdf}
  - fig_vlm_zone_confusion_matrix.{png,pdf}          if available
  - fig_vlm_pesticide_confusion_matrix.{png,pdf}     if available
  - vlm_state_action_table.csv
"""

from __future__ import annotations

import argparse
import json
import math
import re
import textwrap
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

try:
    from PIL import Image
except Exception:
    Image = None


# ============================== Style ==============================
def set_ieee_style():
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif", "Times"],
        "mathtext.fontset": "stix",
        "font.size": 8,
        "axes.labelsize": 8,
        "axes.titlesize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "axes.linewidth": 0.8,
        "lines.linewidth": 1.25,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "savefig.dpi": 600,
        "figure.dpi": 150,
    })


def style_axis(ax):
    ax.tick_params(direction="in", length=3.0, width=0.7)
    ax.grid(True, linewidth=0.35, alpha=0.28)
    for spine in ax.spines.values():
        spine.set_linewidth(0.8)


def save_fig(fig, out_dir: Path, name: str, dpi: int = 600):
    out_dir.mkdir(parents=True, exist_ok=True)
    png = out_dir / f"{name}.png"
    pdf = out_dir / f"{name}.pdf"
    fig.savefig(png, dpi=dpi, bbox_inches="tight", pad_inches=0.03)
    fig.savefig(pdf, bbox_inches="tight", pad_inches=0.03)
    print(f"saved: {png}")
    print(f"saved: {pdf}")


# ============================== Column helpers ==============================
def first_existing(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    for c in candidates:
        if c in df.columns:
            return c
    return None


def clean_name(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def find_image_col(df: pd.DataFrame) -> Optional[str]:
    return first_existing(df, [
        "image_relpath", "front_image_path", "image_path", "rgb_path", "camera_path", "image"
    ])


def resolve_image_path(value, pred_csv: Path, image_root: Optional[Path]) -> Optional[Path]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return None
    p = Path(str(value))
    if p.is_absolute() and p.is_file():
        return p
    for root in [image_root, pred_csv.parent]:
        if root is None:
            continue
        cand = root / p
        if cand.is_file():
            return cand
    return None


def get_zone_cols(df: pd.DataFrame) -> Tuple[Optional[str], Optional[str]]:
    gt_zone = first_existing(df, ["gt_target_zone", "target_zone", "robot_target_zone_id", "gt_zone"])
    pred_zone = first_existing(df, ["pred_target_zone", "pred_zone", "predicted_target_zone"])
    return gt_zone, pred_zone


def get_pesticide_cols(df: pd.DataFrame) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    gt_pest = first_existing(df, ["gt_apply_pesticide", "apply_pesticide", "target_pesticide"])
    pred_pest = first_existing(df, ["pred_apply_pesticide", "pred_pesticide", "predicted_apply_pesticide"])
    prob = first_existing(df, [
        "pred_apply_pesticide_prob", "pred_pesticide_prob", "predicted_apply_pesticide_probability"
    ])
    return gt_pest, pred_pest, prob


def col_has_zone(col: str, zone: int) -> bool:
    s = clean_name(col)
    return any(p in s for p in [f"zone_{zone}", f"zone{zone}", f"z_{zone}", f"z{zone}"])


def find_value_column(df: pd.DataFrame, variable: str, zone: Optional[int], preferred_prefix: str) -> Optional[str]:
    """Robustly find T/H/S columns for a given zone and prefix."""
    var_keys = {
        "temp": ["temp", "temperature"],
        "humidity": ["humidity", "hum", "rh"],
        "soil": ["soil", "moisture"],
    }[variable]
    pref_keys = [preferred_prefix]
    if preferred_prefix == "gt":
        pref_keys += ["target", "true"]

    # prefix + variable + zone
    cands = []
    for c in df.columns:
        s = clean_name(c)
        if not any(pk in s for pk in pref_keys):
            continue
        if not any(vk in s for vk in var_keys):
            continue
        if zone is not None and not col_has_zone(c, zone):
            continue
        cands.append(c)
    if cands:
        return sorted(cands, key=lambda c: ("target_zone" not in clean_name(c), len(c)))[0]

    # variable + zone fallback
    cands = []
    for c in df.columns:
        s = clean_name(c)
        if not any(vk in s for vk in var_keys):
            continue
        if zone is not None and not col_has_zone(c, zone):
            continue
        cands.append(c)
    if cands:
        return sorted(cands, key=len)[0]

    # prefix + variable without zone fallback
    cands = []
    for c in df.columns:
        s = clean_name(c)
        if not any(pk in s for pk in pref_keys):
            continue
        if not any(vk in s for vk in var_keys):
            continue
        cands.append(c)
    if cands:
        return sorted(cands, key=len)[0]

    return None


def safe_float(row: pd.Series, col: Optional[str]) -> Optional[float]:
    if col is None or col not in row.index:
        return None
    try:
        v = float(row[col])
        return v if math.isfinite(v) else None
    except Exception:
        return None


# ============================== State / action interpretation ==============================
def infer_strawberry_state(temp, hum, soil, pest_prob) -> str:
    """Simple interpretable labels for visualization; thresholds are descriptive."""
    if pest_prob is not None and pest_prob >= 0.50:
        return "Disease-risk / treatment"
    if temp is not None and temp >= 28.0:
        return "Heat stress"
    if temp is not None and temp <= 19.0:
        return "Cold stress"
    if soil is not None and soil <= 55.0:
        return "Dry-soil stress"
    if soil is not None and soil >= 82.0:
        return "Over-wet soil"
    if hum is not None and hum >= 85.0:
        return "High-humidity risk"
    if hum is not None and hum <= 45.0:
        return "Low-humidity stress"
    return "Healthy / monitor"


def infer_vlm_action(zone: int, state: str, pred_pest, pest_prob) -> str:
    if pred_pest is not None and int(pred_pest) == 1:
        return f"Apply pesticide in Z{zone}"
    if "Dry-soil" in state:
        return f"Irrigate Z{zone}"
    if "Heat" in state:
        return f"Cool/ventilate Z{zone}"
    if "Cold" in state:
        return f"Heat Z{zone}"
    if "High-humidity" in state or "Over-wet" in state:
        return f"Ventilate/reduce water Z{zone}"
    if "Low-humidity" in state:
        return f"Increase humidity Z{zone}"
    return f"Monitor Z{zone}"


def build_state_action_table(df: pd.DataFrame) -> pd.DataFrame:
    gt_zone_col, pred_zone_col = get_zone_cols(df)
    _, pred_pest_col, prob_col = get_pesticide_cols(df)

    rows = []
    for i, row in df.iterrows():
        zone = safe_float(row, pred_zone_col)
        if zone is None:
            zone = safe_float(row, gt_zone_col)
        zone = int(max(1, min(4, round(zone if zone is not None else 1))))

        pred_pest = safe_float(row, pred_pest_col)
        pred_pest_int = None if pred_pest is None else int(round(pred_pest))

        pest_prob = safe_float(row, prob_col)
        if pest_prob is None and pred_pest_int is not None:
            pest_prob = float(pred_pest_int)

        # Predicted target-zone state is preferred. GT is fallback.
        temp_col = find_value_column(df, "temp", zone, "pred") or find_value_column(df, "temp", zone, "gt")
        hum_col = find_value_column(df, "humidity", zone, "pred") or find_value_column(df, "humidity", zone, "gt")
        soil_col = find_value_column(df, "soil", zone, "pred") or find_value_column(df, "soil", zone, "gt")

        temp = safe_float(row, temp_col)
        hum = safe_float(row, hum_col)
        soil = safe_float(row, soil_col)

        state = infer_strawberry_state(temp, hum, soil, pest_prob)
        action = infer_vlm_action(zone, state, pred_pest_int, pest_prob)

        rows.append({
            "row_idx": i,
            "sample_idx": row["sample_idx"] if "sample_idx" in df.columns else i,
            "pred_zone": zone,
            "pred_pesticide": pred_pest_int,
            "pesticide_prob": pest_prob,
            "temperature": temp,
            "humidity": hum,
            "soil_moisture": soil,
            "state": state,
            "vlm_action": action,
        })
    return pd.DataFrame(rows)


# ============================== Plots ==============================
def plot_decision_timeline(df: pd.DataFrame, out_dir: Path, metrics: Dict, dpi: int):
    gt_zone_col, pred_zone_col = get_zone_cols(df)
    gt_pest_col, pred_pest_col, prob_col = get_pesticide_cols(df)
    x = np.arange(len(df))

    fig, axes = plt.subplots(2, 1, figsize=(7.2, 4.2), sharex=True,
                             gridspec_kw={"height_ratios": [1, 1], "hspace": 0.12})

    ax = axes[0]
    if gt_zone_col:
        ax.step(x, df[gt_zone_col].to_numpy(float), where="post", color="black", linewidth=1.5)
    if pred_zone_col:
        ax.step(x, df[pred_zone_col].to_numpy(float), where="post", color="red", linestyle="--", linewidth=1.5)
    ax.set_ylabel("Target zone")
    ax.set_yticks([1, 2, 3, 4])
    ax.set_ylim(0.6, 4.4)
    style_axis(ax)
    txt = []
    if "zone_accuracy" in metrics:
        txt.append(f"Zone Acc. = {100*float(metrics['zone_accuracy']):.1f}%")
    if "zone_macro_f1" in metrics:
        txt.append(f"Macro-F1 = {float(metrics['zone_macro_f1']):.3f}")
    if txt:
        ax.text(0.02, 0.96, "\n".join(txt), transform=ax.transAxes, va="top",
                bbox=dict(facecolor="white", edgecolor="0.5", alpha=0.9, boxstyle="round,pad=0.25"))
    ax.text(1.01, 0.78, "GT", transform=ax.transAxes, color="black", va="center")
    ax.text(1.01, 0.62, "VLM", transform=ax.transAxes, color="red", va="center")

    ax = axes[1]
    if gt_pest_col:
        ax.step(x, df[gt_pest_col].to_numpy(float), where="post", color="black", linewidth=1.5)
    if prob_col:
        ax.plot(x, df[prob_col].to_numpy(float), color="red", linewidth=1.5)
    elif pred_pest_col:
        ax.step(x, df[pred_pest_col].to_numpy(float), where="post", color="red", linestyle="--", linewidth=1.5)
    ax.axhline(0.5, color="0.45", linewidth=0.8, linestyle=":")
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("Sample index")
    ax.set_ylabel("Pesticide output")
    style_axis(ax)
    txt = []
    if "pesticide_accuracy" in metrics:
        txt.append(f"Pesticide Acc. = {100*float(metrics['pesticide_accuracy']):.1f}%")
    if "pesticide_f1" in metrics:
        txt.append(f"F1 = {float(metrics['pesticide_f1']):.3f}")
    if txt:
        ax.text(0.02, 0.96, "\n".join(txt), transform=ax.transAxes, va="top",
                bbox=dict(facecolor="white", edgecolor="0.5", alpha=0.9, boxstyle="round,pad=0.25"))
    ax.text(1.01, 0.76, "GT", transform=ax.transAxes, color="black", va="center")
    ax.text(1.01, 0.60, "VLM", transform=ax.transAxes, color="red", va="center")

    save_fig(fig, out_dir, "fig_vlm_decision_timeline", dpi)
    plt.close(fig)


def plot_state_action_timeline(state_df: pd.DataFrame, out_dir: Path, dpi: int):
    x = np.arange(len(state_df))
    base_actions = []
    for a in state_df["vlm_action"].astype(str):
        base = re.sub(r"\s+Z[1-4]$", "", a)
        if base not in base_actions:
            base_actions.append(base)
    code = {a: i+1 for i, a in enumerate(base_actions)}
    y = np.array([code[re.sub(r"\s+Z[1-4]$", "", a)] for a in state_df["vlm_action"].astype(str)], dtype=float)

    fig, ax = plt.subplots(figsize=(7.2, 2.8))
    ax.step(x, y, where="post", color="black", linewidth=1.4)
    pest = state_df["pred_pesticide"].fillna(0).to_numpy(int) if "pred_pesticide" in state_df else np.zeros(len(x), int)
    idx = np.where(pest == 1)[0]
    if len(idx):
        ax.scatter(idx, y[idx], s=14, color="red", zorder=4)
    ax.set_xlabel("Sample index")
    ax.set_ylabel("VLM action")
    ax.set_yticks(list(code.values()))
    ax.set_yticklabels(list(code.keys()))
    ax.set_ylim(0.5, len(code)+0.5)
    style_axis(ax)
    ax.text(0.02, 0.96, "Red markers: pesticide ON", transform=ax.transAxes, va="top",
            bbox=dict(facecolor="white", edgecolor="0.5", alpha=0.9, boxstyle="round,pad=0.25"))
    save_fig(fig, out_dir, "fig_vlm_state_action_timeline", dpi)
    plt.close(fig)


def load_image(path: Optional[Path]):
    if path is None or Image is None:
        return None
    try:
        return np.asarray(Image.open(path).convert("RGB"))
    except Exception:
        return None


def plot_storyboard(df: pd.DataFrame, state_df: pd.DataFrame, pred_csv: Path, image_root: Optional[Path], out_dir: Path, max_examples: int, dpi: int):
    image_col = find_image_col(df)
    n = len(df)
    if n == 0:
        return
    count = min(max_examples, n)

    # Prefer decision/state changes; otherwise uniform sampling.
    change = [0]
    prev = (state_df.iloc[0]["state"], state_df.iloc[0]["vlm_action"])
    for i in range(1, n):
        cur = (state_df.iloc[i]["state"], state_df.iloc[i]["vlm_action"])
        if cur != prev:
            change.append(i)
            prev = cur
    if len(change) >= count:
        idxs = [change[i] for i in np.linspace(0, len(change)-1, count, dtype=int)]
    else:
        idxs = np.linspace(0, n-1, count, dtype=int).tolist()

    cols = min(4, count)
    rows = int(math.ceil(count / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(7.2, max(2.0, 2.15*rows)))
    axes = np.atleast_1d(axes).reshape(rows, cols)
    for ax in axes.flat:
        ax.set_axis_off()

    for k, idx in enumerate(idxs):
        ax = axes[k // cols, k % cols]
        row = df.iloc[idx]
        st = state_df.iloc[idx]
        img_arr = None
        if image_col is not None:
            img_arr = load_image(resolve_image_path(row[image_col], pred_csv, image_root))
        if img_arr is not None:
            ax.imshow(img_arr)
        else:
            ax.add_patch(Rectangle((0,0), 1, 1, facecolor="0.92", edgecolor="0.5"))
            ax.text(0.5, 0.5, "image\nnot found", ha="center", va="center")
            ax.set_xlim(0, 1); ax.set_ylim(0, 1)

        prob = st["pesticide_prob"]
        prob_txt = "n/a" if pd.isna(prob) else f"{float(prob):.2f}"
        vals = []
        if not pd.isna(st["temperature"]): vals.append(f"T={float(st['temperature']):.1f}°C")
        if not pd.isna(st["humidity"]): vals.append(f"H={float(st['humidity']):.0f}%")
        if not pd.isna(st["soil_moisture"]): vals.append(f"S={float(st['soil_moisture']):.0f}%")

        cap = f"#{int(st['sample_idx'])} | Z{int(st['pred_zone'])} | P={prob_txt}\n{st['state']}\n{st['vlm_action']}"
        if vals:
            cap += "\n" + ", ".join(vals)
        ax.text(0.02, 0.98, textwrap.fill(cap, width=25), transform=ax.transAxes,
                ha="left", va="top", fontsize=7,
                bbox=dict(facecolor="white", edgecolor="0.3", alpha=0.86, pad=2))

    fig.suptitle("VLM decision examples: strawberry state and selected action", fontsize=9, y=0.995)
    fig.tight_layout(pad=0.25)
    save_fig(fig, out_dir, "fig_vlm_state_action_storyboard", dpi)
    plt.close(fig)


def plot_metrics_panel(metrics: Dict, out_dir: Path, dpi: int):
    names, vals = [], []
    for label, key in [
        ("Zone accuracy", "zone_accuracy"),
        ("Zone macro-F1", "zone_macro_f1"),
        ("Pesticide accuracy", "pesticide_accuracy"),
        ("Pesticide F1", "pesticide_f1"),
    ]:
        if key in metrics:
            names.append(label); vals.append(float(metrics[key]))
    fig, ax = plt.subplots(figsize=(3.5, 2.35))
    if names:
        y = np.arange(len(names))
        ax.barh(y, vals, color="0.2")
        ax.set_yticks(y); ax.set_yticklabels(names)
        ax.invert_yaxis(); ax.set_xlim(0, 1.05)
        ax.set_xlabel("Score")
        style_axis(ax)
        for yi, v in zip(y, vals):
            ax.text(v + 0.015, yi, f"{v:.3f}", va="center")
    else:
        ax.set_axis_off(); ax.text(0.5, 0.5, "No metrics found", ha="center", va="center")
    if "regression_mae_overall" in metrics:
        ax.text(0.02, 0.04, f"Regression MAE = {float(metrics['regression_mae_overall']):.3f}",
                transform=ax.transAxes, ha="left", va="bottom",
                bbox=dict(facecolor="white", edgecolor="0.5", alpha=0.9))
    save_fig(fig, out_dir, "fig_vlm_metrics_summary", dpi)
    plt.close(fig)


def plot_confusion_matrix(cm: List[List[int]], labels: List[str], title: str, out_dir: Path, name: str, dpi: int):
    arr = np.asarray(cm, dtype=float)
    fig, ax = plt.subplots(figsize=(2.7, 2.45))
    im = ax.imshow(arr, cmap="Greys", aspect="equal")
    ax.set_xticks(np.arange(len(labels))); ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels); ax.set_yticklabels(labels)
    ax.set_xlabel("Predicted"); ax.set_ylabel("Ground truth")
    ax.set_title(title, fontsize=8)
    style_axis(ax)
    maxv = max(1.0, float(arr.max()) if arr.size else 1.0)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            color = "white" if arr[i, j] > 0.55*maxv else "black"
            ax.text(j, i, f"{int(arr[i,j])}", ha="center", va="center", color=color)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    save_fig(fig, out_dir, name, dpi)
    plt.close(fig)


# ============================== Main ==============================
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--pred_csv", type=str, required=True)
    p.add_argument("--metrics_json", type=str, default=None)
    p.add_argument("--image_root", type=str, default=None)
    p.add_argument("--out_dir", type=str, default=None)
    p.add_argument("--max_story_examples", type=int, default=8)
    p.add_argument("--dpi", type=int, default=600)
    return p.parse_args()


def main():
    args = parse_args()
    set_ieee_style()

    pred_csv = Path(args.pred_csv).expanduser().resolve()
    metrics_json = Path(args.metrics_json).expanduser().resolve() if args.metrics_json else pred_csv.parent / "metrics.json"
    image_root = Path(args.image_root).expanduser().resolve() if args.image_root else None
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else pred_csv.parent / "ieee_vla_decision_figures"
    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(pred_csv)
    metrics = json.loads(metrics_json.read_text()) if metrics_json.is_file() else {}

    state_df = build_state_action_table(df)
    state_table = out_dir / "vlm_state_action_table.csv"
    state_df.to_csv(state_table, index=False)

    plot_decision_timeline(df, out_dir, metrics, args.dpi)
    plot_state_action_timeline(state_df, out_dir, args.dpi)
    plot_storyboard(df, state_df, pred_csv, image_root, out_dir, args.max_story_examples, args.dpi)
    plot_metrics_panel(metrics, out_dir, args.dpi)

    if "zone_confusion_matrix_1_based_rows_true_cols_pred" in metrics:
        plot_confusion_matrix(metrics["zone_confusion_matrix_1_based_rows_true_cols_pred"],
                              ["Z1", "Z2", "Z3", "Z4"], "Target-zone decision", out_dir,
                              "fig_vlm_zone_confusion_matrix", args.dpi)
    if "pesticide_confusion_matrix_rows_true_cols_pred" in metrics:
        plot_confusion_matrix(metrics["pesticide_confusion_matrix_rows_true_cols_pred"],
                              ["Off", "On"], "Pesticide decision", out_dir,
                              "fig_vlm_pesticide_confusion_matrix", args.dpi)

    print("\nDone.")
    print(f"Input predictions: {pred_csv}")
    print(f"Input metrics:     {metrics_json}")
    print(f"Output directory:  {out_dir}")
    print(f"State/action CSV:  {state_table}")


if __name__ == "__main__":
    main()